### ISSUE TITLE
I can't show tabs

### ISSUE THREAD

**Issue by cruzcraul** [krissss/yii2-adminlte-iframe-mode#1]
Hi @krissss 

I tried to follow your steps to make it work in iframe mode but I have not succeeded.
I have analyzed your code a bit and I can not find the divs in the example view: content-iframe, menu-tabs, iframe-layout.

Is there something you omitted in the documentation? Do I need to add some dependence to make it work?

Thank you!

**Comment by krissss** [comment]
sorry, the old one is not updated. current example [example-views/main-content.php](https://github.com/krissss/yii2-adminlte-iframe-mode/blob/master/example-views/main-content.php) is updated.

**Comment by cruzcraul** [comment]
Thank you @krissss, now it works! :sunglasses:
